name: auto-commit-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Build dist
      run: |
        yarn
        yarn test
        if [ $? == 0 ]; then
          echo "Yarn test passed";
          echo "Building package.."

          yarn build

          if [ $? != 0 ]; then
            echo "Yarn build failed"
            echo "Aborting"
            exit 1
          fi

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add -f dist/dexcom-share-api.es.js dist/dexcom-share-api.umd.js
          git commit -m "<auto-committer> Update dist"
          git push -f origin HEAD:main
        else
          echo "Yarn test failed"
          echo "Aborting"
          exit 1
        fi
