name: auto-commit-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build dist
      run: |
        yarn
        yarn test
        if [ $? == 0 ]; then
          echo "Yarn test passed";
          echo "Building package.."

          yarn build

          if [ $? != 0 ]; then
            echo "Yarn build failed"
            echo "Aborting"
            exit 1
          fi

          git add dist/dexcom-share-api.es.js dist/dexcom-share-api.umd.js
          git commit -m "<auto-committer> Update dist"
          git push -u origin main
        else
          echo "Yarn test failed"
          echo "Aborting"
          exit 1
        fi
